[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
xiangqi_match = "4EcbVv7UbxnTb8tDbRkb6iUmahhUav8ccv1dCSgE6VVW"

[programs.devnet]
xiangqi_match = "4EcbVv7UbxnTb8tDbRkb6iUmahhUav8ccv1dCSgE6VVW"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/xiangqi_match"]
